# fly.toml app configuration file generated for caffeinecrash
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'caffeinecrash'
primary_region = 'iad'

[build]

[env]
  APP_NAME = "CAFFEINECRASH"
  DEBUG = "false"
  HASH_ALGO = "PASSWORD_ARGON2ID"
  SESSION_NAME = "CAFFEINECRASH_SESSION"
  SESSION_LIFETIME = "3600"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
  source = 'caffeinecrash_data'
  destination = '/var/www/html/data'
